### ISSUE TITLE
Possible way to blacklist certain enemies?

### ISSUE THREAD

**Issue by Fellow9000** [NoteBoxz/LCMoniterEnemies#1]
Using Lethalmin, would blacklisting Pikmin be possible? There are far too many to cycle through.

**Comment by NoteBoxz** [comment]
Set this config option to True
![image](https://github.com/user-attachments/assets/9ba14c65-60b5-48cb-b9e5-cd9daeb873c5)

**Comment by Fellow9000** [comment]
Thank you
